version: '3'

services:
  webserver:
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /home/soulforger/frontend-deployments/nginx/conf:/etc/nginx/conf.d/:ro
      - /home/soulforger/frontend-deployments/certbot/conf/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /home/soulforger/frontend-deployments/certbot/www/:/var/www/certbot/:rw
      - /home/soulforger/frontend-deployments/certbot/conf/:/etc/letsencrypt/:rw